import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { FassGeneratedModule, FassGeneratedSharedModule } from './generated/module';
import { FassValidator, registerValidationChecks } from './fass-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type FassAddedServices = {
    validation: {
        FassValidator: FassValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type FassServices = LangiumServices & FassAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const FassModule: Module<FassServices, PartialLangiumServices & FassAddedServices> = {
    validation: {
        FassValidator: () => new FassValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createFassServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Fass: FassServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        FassGeneratedSharedModule
    );
    const Fass = inject(
        createDefaultModule({ shared }),
        FassGeneratedModule,
        FassModule
    );
    shared.ServiceRegistry.register(Fass);
    registerValidationChecks(Fass);
    return { shared, Fass };
}
