"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Vec3_1 = require("../Vec3");
const Player_1 = require("../Player");
const Movement_1 = require("../Movement");
const player = new Player_1.Player(true, "JairusSW", 3022, new Vec3_1.Vec3(1, 2, 3), new Movement_1.Movement(true, 6.0, new Movement_1.Direction(5.0, 4.0, 9.0)), [1, 2, 3, 4]);
const buf = new ArrayBuffer(Player_1.Player.__FASS_SIZE);
Player_1.Player.__FASS_SERIALIZE(buf, player);
console.log("Serialized Player: " + Uint8Array.wrap(buf).join(" "));
const p2 = new Player_1.Player(false, "        ", 0, new Vec3_1.Vec3(0, 0, 0), new Movement_1.Movement(false, 0, new Movement_1.Direction(0, 0, 0)), [0, 0, 0, 0]); //changetype<Player>(__new(offsetof<Player>(), idof<Player>()));
Player_1.Player.__FASS_DESERIALIZE(buf, p2);
Player_1.Player.__FASS_SERIALIZE(buf, p2);
console.log("Deserialized Player: " + Uint8Array.wrap(buf).join(" "));
